# Sample .travis.yml for R projects from https://github.com/craigcitro/r-travis

sudo: required

language: c

before_install:
  - curl -OL http://raw.github.com/craigcitro/r-travis/master/scripts/travis-tool.sh
  - chmod 755 ./travis-tool.sh
  - ./travis-tool.sh bootstrap
  - ./travis-tool.sh nstall_github hadley/lubridate

install:
  - ./travis-tool.sh install_deps

script: ./travis-tool.sh run_tests && Rscript -e "lubridate::round_date(Sys.time(),'minute')"

after_failure:
  - ./travis-tool.sh dump_logs

after_script:
  - ./travis-tool.sh dump_sysinfo

env:
  - WARNINGS_ARE_ERRORS=1 R_BUILD_ARGS="--no-manual" R_CHECK_ARGS="--no-manual --as-cran"
